### ISSUE TITLE
why the newly published post doesn't appear in the webpage?

### ISSUE THREAD

**Issue by luckypoem** [fcanas/bake#1]
hi.

i installed ur app: http://surmount.biz.st:9837/ ,but he newly published posts(http://surmount.biz.st:9837/blog/test-1.html and http://surmount.biz.st:9837/blog/test-2.html ) doesn't appear in the webpage?

**Comment by fcanas** [comment]
I see them there. Did you resolve the issue?

**Comment by luckypoem** [comment]
i mean why they don't appear in the homepage: http://surmount.biz.st:9837 automatically?

**Comment by fcanas** [comment]
The homepage's content isn't populated automatically. The content of index.html is the processed output of `index.md`. If you want to see links to those pages on the homepage, add them in markdown to `index.md`.

**Comment by luckypoem** [comment]
i see.and i found ur bog: http://www.fabiancanas.com/blog/ ,which blog app do u use to build it?
thanks

**Comment by dheadshot** [comment]
I created a [fork](https://codeberg.org/dheadshot/Structured-Bake-Alike) which incidentally resolves this issue alongside making a lot of changes to fit my own needs.  I kept the original licence etc, so I hope this is OK.
